.PHONY: test-all-patterns
test-all-patterns:
	go test ./strategy
	go test ./factory_method
	go test ./adapter
	go test ./prototype
	go test ./builder
	go test -v ./composite
	go test ./facade
	go test ./state
	go test -v ./proxy
	go test -v ./command
